// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MqttMessage struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MqttMessage) Reset()         { *m = MqttMessage{} }
func (m *MqttMessage) String() string { return proto.CompactTextString(m) }
func (*MqttMessage) ProtoMessage()    {}
func (*MqttMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *MqttMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MqttMessage.Unmarshal(m, b)
}
func (m *MqttMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MqttMessage.Marshal(b, m, deterministic)
}
func (m *MqttMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MqttMessage.Merge(m, src)
}
func (m *MqttMessage) XXX_Size() int {
	return xxx_messageInfo_MqttMessage.Size(m)
}
func (m *MqttMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MqttMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MqttMessage proto.InternalMessageInfo

func (m *MqttMessage) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *MqttMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*MqttMessage)(nil), "proto.mqtt.MqttMessage")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0x7a, 0xb9, 0x85, 0x25, 0x25, 0x52, 0x32,
	0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25,
	0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0x95, 0x52, 0xd2, 0x50, 0x59, 0x30, 0x2f, 0xa9, 0x34,
	0x4d, 0x3f, 0x35, 0xb7, 0xa0, 0xa4, 0x12, 0x2a, 0x29, 0x8f, 0x2e, 0x59, 0x92, 0x99, 0x9b, 0x5a,
	0x5c, 0x92, 0x98, 0x5b, 0x00, 0x51, 0xa0, 0xe4, 0xc8, 0xc5, 0xed, 0x5b, 0x58, 0x52, 0xe2, 0x9b,
	0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0x24, 0xc1, 0xc5, 0x9e, 0x9c, 0x9f, 0x9b, 0x9b, 0x98, 0x97,
	0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x82, 0x64, 0x72, 0x21, 0x8a, 0x24, 0x98,
	0x14, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x27, 0xf6, 0x28, 0x56, 0x88, 0xf1, 0x6c, 0x60, 0xca,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x7b, 0x16, 0x14, 0xc7, 0x00, 0x00, 0x00,
}
